# Clock signal
#set_property PACKAGE_PIN W5 [get_ports {clk}]							
#set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets write_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets write_IBUF]
#Clock
set_property PACKAGE_PIN W5 [get_ports {i_Clk}]					
set_property IOSTANDARD LVCMOS33 [get_ports {i_Clk}]
#Write
set_property PACKAGE_PIN U18 [get_ports {write}]					
set_property IOSTANDARD LVCMOS33 [get_ports {write}]
#out serial
set_property PACKAGE_PIN A18 [get_ports {out_serial}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {out_serial}]
#In serial
set_property PACKAGE_PIN B18 [get_ports {in_serial}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {in_serial}]
#Out done
#set_property PACKAGE_PIN U3 [get_ports {mode_input}]                    
#set_property IOSTANDARD LVCMOS33 [get_ports {mode_input}]
#Out active
#set_property PACKAGE_PIN W3 [get_ports {mode_display}]                    
#set_property IOSTANDARD LVCMOS33 [get_ports {mode_display}]
#set_property PACKAGE_PIN V13 [get_ports {mode_flag}]                    
#set_property IOSTANDARD LVCMOS33 [get_ports {mode_flag}]

set_property PACKAGE_PIN V14 [get_ports {show_input[7]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {show_input[7]}]
set_property PACKAGE_PIN U14 [get_ports {show_input[6]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {show_input[6]}]
set_property PACKAGE_PIN U15 [get_ports {show_input[5]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {show_input[5]}]
set_property PACKAGE_PIN W18 [get_ports {show_input[4]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {show_input[4]}]
set_property PACKAGE_PIN V19 [get_ports {show_input[3]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {show_input[3]}]
set_property PACKAGE_PIN U19 [get_ports {show_input[2]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {show_input[2]}]
set_property PACKAGE_PIN E19 [get_ports {show_input[1]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {show_input[1]}]
set_property PACKAGE_PIN U16 [get_ports {show_input[0]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {show_input[0]}]


              set_property PACKAGE_PIN L1 [get_ports {out1[7]}] 
              set_property IOSTANDARD LVCMOS33 [get_ports {out1[7]}]
              set_property PACKAGE_PIN P1 [get_ports {out1[6]}] 
              set_property IOSTANDARD LVCMOS33 [get_ports {out1[6]}]
              set_property PACKAGE_PIN N3 [get_ports {out1[5]}] 
              set_property IOSTANDARD LVCMOS33 [get_ports {out1[5]}]
              set_property PACKAGE_PIN P3 [get_ports {out1[4]}] 
              set_property IOSTANDARD LVCMOS33 [get_ports {out1[4]}]
              set_property PACKAGE_PIN U3 [get_ports {out1[3]}] 
              set_property IOSTANDARD LVCMOS33 [get_ports {out1[3]}]
              set_property PACKAGE_PIN W3 [get_ports {out1[2]}] 
              set_property IOSTANDARD LVCMOS33 [get_ports {out1[2]}]
              set_property PACKAGE_PIN V3 [get_ports {out1[1]}] 
              set_property IOSTANDARD LVCMOS33 [get_ports {out1[1]}]
              set_property PACKAGE_PIN V13 [get_ports {out1[0]}] 
              set_property IOSTANDARD LVCMOS33 [get_ports {out1[0]}]
